---
# tasks file for confluence

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - confluence

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - confluence

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - confluence

- name: Create Confluence group
  become: yes
  group:
    name: confluence
    state: present
  tags:
    - confluence

- name: Create Confluence user
  become: yes
  user:
    name: confluence
    group: confluence
    comment: "Confluence user"
    home: "{{ confluence_home_dir }}"
    shell: /bin/bash
    createhome: no
  tags:
    - confluence

- name: Create Confluence working directory
  become: yes
  file:
    path: "{{ confluence_work_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags:
    - confluence

- name: Create Confluence install directory
  become: yes
  file:
    path: "{{ confluence_install_dir }}"
    owner: confluence
    group: confluence
    mode: 0755
    state: directory
  tags:
    - confluence

- name: Create Confluence home directory
  become: yes
  file:
    path: "{{ confluence_home_dir }}"
    owner: confluence
    group: confluence
    mode: 0755
    state: directory
  tags:
    - confluence

- name: Download Confluence
  become: yes
  get_url:
    url: "{{ confluence_download_url }}"
    dest: "{{ confluence_work_dir }}/{{ confluence_archive }}"
    sha256sum: "{{ confluence_archive_sha256sum }}"
  tags:
    - confluence

- name: Extract Confluence to install directory
  become: yes
  unarchive:
    src: "{{ confluence_work_dir }}/{{ confluence_archive }}"
    dest: "{{ confluence_install_dir }}"
    owner: confluence
    group: confluence
    mode: 0755
    copy: no
    creates: "{{ confluence_install_dir }}/atlassian-confluence-{{ confluence_version }}"
  tags:
    - confluence

- name: Create symlink for current version
  become: yes
  file:
    src: "{{ confluence_install_dir }}/atlassian-confluence-{{ confluence_version }}"
    dest: "{{ confluence_install_dir }}/current"
    state: link
  tags:
    - confluence

- name: Create Confluence init properties
  become: yes
  template:
    src: confluence-init.properties.j2
    dest: "{{ confluence_install_dir }}/atlassian-confluence-{{ confluence_version }}/confluence/WEB-INF/classes/confluence-init.properties"
    owner: confluence
    group: confluence
    mode: 0644
  notify:
    - restart confluence
  tags:
    - confluence

- name: Set Confluence environment settings
  become: yes
  template:
    src: setenv.sh.j2
    dest: "{{ confluence_install_dir }}/atlassian-confluence-{{ confluence_version }}/bin/setenv.sh"
    owner: confluence
    group: confluence
    mode: 0755
  notify:
    - restart confluence
  tags:
    - confluence

- name: Create Confluence init script
  become: yes
  template:
    src: confluence.j2
    dest: /etc/init.d/confluence
    owner: root
    group: root
    mode: 0755
  tags:
    - confluence

- name: Ensure Confluence service is started and enabled on boot
  become: yes
  service:
    name: confluence
    state: started
    pattern: '/usr/bin/java -Djava.util.logging.config.file=/opt/atlassian/confluence/atlassian-confluence-{{ confluence_version }}/conf/logging.properties'
    enabled: yes
  tags:
    - confluence
